name: Check pull request

on:
  pull_request_target:
    types:
      - opened
      - edited
      - labeled
      - unlabeled
      - synchronize

jobs:
  check:
    uses: zeshuaro/github-actions-workflows/.github/workflows/check-pull-request.yml@f38c53a9a689b989e617cf72f3c91322639219d0
