name: Label pull request

on:
  pull_request_target:
    types:
      - opened

jobs:
  label:
    uses: zeshuaro/github-actions-workflows/.github/workflows/label-pull-request.yml@9e2c06558435e12cf64e73dd210306b4883aafdd
