name: Scheduled jobs

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    name: Close stale
    uses: zeshuaro/github-actions-workflows/.github/workflows/close-stale.yml@f38c53a9a689b989e617cf72f3c91322639219d0
  lock:
    name: Lock threads
    uses: zeshuaro/github-actions-workflows/.github/workflows/lock-threads.yml@f38c53a9a689b989e617cf72f3c91322639219d0
