name: Scheduled jobs

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    name: Close stale
    uses: zeshuaro/github-actions-workflows/.github/workflows/close-stale.yml@de1d095ed7299374421389eae787b7720efea5c6
  lock:
    name: Lock threads
    uses: zeshuaro/github-actions-workflows/.github/workflows/lock-threads.yml@de1d095ed7299374421389eae787b7720efea5c6
