name: Scheduled actions

on:
  schedule:
    - cron: "0 8 * * *"

jobs:
  scheduled:
    uses: zeshuaro/github-actions-workflows/.github/workflows/scheduled.yml@d039a20aa1d98fa44f20e6b67c078c4c0a01227e
